[tool.poetry]
name = "casus-networking"
version = "0.1.0"
description = ""
authors = ["requinard <david@requinard.nl>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
